INSERT INTO role (id, name) VALUES (UUID(), 'ROLE_ADMIN');
INSERT INTO role (id, name) VALUES (UUID(), 'ROLE_MANAGER');
INSERT INTO role (id, name) VALUES (UUID(), 'ROLE_EMPLOYER');
INSERT INTO role (id, name) VALUES (UUID(), 'ROLE_USER');